module_name: Mapbox
author_name: Mapbox
author_url: https://www.mapbox.com/
github_url: https://github.com/mapbox/mapbox-gl-native
dash_url: https://www.mapbox.com/ios-sdk/docsets/Mapbox.xml
copyright: '© 2014–2016 [Mapbox](https://www.mapbox.com/). See [license](https://github.com/mapbox/mapbox-gl-native/blob/master/LICENSE.md) for more details.'

custom_head: |
  <link rel='shortcut icon' href='http://www.mapbox.com/img/favicon.ico' type='image/x-icon' />

objc_mode: Yes
skip_undocumented: Yes
hide_documentation_coverage: Yes
umbrella_header: include/mbgl/ios/Mapbox.h
framework_root: include/mbgl/darwin

custom_categories:
  - name: Map
    children:
      - MGLAccountManager
      - MGLMapCamera
      - MGLMapView
      - MGLMapViewDelegate
      - MGLStyle
      - MGLUserTrackingMode
  - name: Annotations
    children:
      - MGLAnnotation
      - MGLAnnotationImage
      - MGLCalloutView
      - MGLCalloutViewDelegate
      - MGLMultiPoint
      - MGLPointAnnotation
      - MGLPolygon
      - MGLPolyline
      - MGLOverlay
      - MGLShape
      - MGLUserLocation
  - name: Geometry
    children:
      - MGLCoordinateBounds
      - MGLCoordinateBoundsEqualToCoordinateBounds
      - MGLCoordinateBoundsGetCoordinateSpan
      - MGLCoordinateBoundsIsEmpty
      - MGLCoordinateBoundsMake
      - MGLCoordinateBoundsOffset
      - MGLCoordinateSpan
      - MGLCoordinateSpanEqualToCoordinateSpan
      - MGLCoordinateSpanMake
      - MGLCoordinateSpanZero
      - MGLDegreesFromRadians
      - MGLRadiansFromDegrees
      - MGLStringFromCoordinateBounds
