# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

fastlane_version "2.60.0"
opt_out_usage

default_platform :ios

project = "ios.xcodeproj"
plist = "app/Info.plist"
identifier = "com.mapbox.MapboxGL-nightly"
teamid = ENV['FASTLANE_TEAM_ID']

platform :ios do
  before_all do
    update_fastlane
    update_info_plist(display_name: "Nightly", app_identifier: identifier, plist_path: plist, xcodeproj: project)
    update_app_identifier(app_identifier: identifier, plist_path: plist, xcodeproj: project)
    update_project_team(path: project, teamid: teamid)
    set_info_plist_value(path: plist, key: "MAPBOX_ACCESS_TOKEN", value: ENV['MAPBOX_ACCESS_TOKEN'])
  end

  desc "Submit a new build to Apple TestFlight."
  lane :beta do
    increment_build_number(build_number: 1)#Time.now.strftime("%Y%m%d"))
    gym(scheme: "iosapp", include_bitcode: true)
    pilot(skip_waiting_for_build_processing: true)
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
